# Nombre que le daremos al Workflow. Puede ser el nombre que se desee.
name: Ejecuci칩n simple de shell Commands.

# Se especifica la acci칩n o acciones que desencadenar치n este script, por ejemplo `push`, `pull-request`
on: [push]

# Se agregan todos los jobs a ejecutar cada vez que se realice un push en el repositorio
jobs:
  # Este es un job, se le da el nombre deseado, por ejemplo "job-de-prueba"
  job-de-prueba:
    # Se debe indicar el SO en el que se desea ejecutar las tareas de este job
    runs-on: ubuntu-latest
    # A continuaci칩n se especifican los pasos que se deben realizar de forma secuencial
    steps:
      - name: Solo imprimir una cadena simple
        run: echo "Hola Mundo que tal!"
      - name: Una segunda actividad
        run: |
          node -v
          nom -v
